# NOTE: In doc/source/contributor/testing/ci_scenario_jobs.rst file there is
# document with summary of all tempest, neutron-tempest-plugin and grenade jobs
# summary.
# Please update this document always when any changes to jobs are made.
- project:
    templates:
      - neutron-tempest-plugin-jobs-zed
      - openstack-cover-jobs
      - openstack-python3-zed-jobs
      - openstack-python3-zed-jobs-arm64
      - publish-openstack-docs-pti
      - periodic-stable-jobs
      - check-requirements
      - release-notes-jobs-python3
      - neutron-experimental-jobs
      - neutron-periodic-jobs
      - neutron-tox-override-jobs
    check:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-ovs-rally-task
          # TODO: re enable once jobs fixed
          #- neutron-ovs-grenade-multinode:
          #  voting: false
          #- neutron-ovs-grenade-dvr-multinode:
          #  voting: false
        - neutron-ovs-tempest-multinode-full
        - neutron-ovs-tempest-dvr-ha-multinode-full
        - neutron-ovn-tempest-ipv6-only
        - neutron-ovn-rally-task:
            voting: false
    gate:
      jobs:
        - neutron-functional-with-uwsgi
        - neutron-fullstack-with-uwsgi
        - neutron-ovs-tempest-multinode-full
          #- neutron-ovs-grenade-multinode:
          #  voting: false
          #- neutron-ovs-grenade-dvr-multinode:
          #  voting: false
        - neutron-ovn-tempest-ipv6-only
